# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Brian Bai 
email: brian.baitq@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog is my personal blog about DataScience, Python, Spark. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://brian-bai.github.io" # the base hostname & protocol for your site
twitter_username: Brian_Bai 
github_username:  brian-bai

# Build settings
markdown: kramdown
